# Copyright (c) 2026 Shawn Stricker
"""Emulated Anker Solix BLE devices for testing BLE clients through bleak."""

from .backend import (
    COMMAND_UUID,
    GATT_SERVICE_UUID,
    TELEMETRY_UUID,
    EmulatedBleakBackend,
)
from .clock import Clock, ManualClock, MonotonicClock
from .devices import (
    A17C0,
    A17C1,
    A17C3,
    A25X7,
    A91B2,
    A110B,
    A1722,
    A1761,
    A1763,
    A1765,
    A1780,
    A1783,
    A1785,
    A2345,
    A2687,
    AS220,
    DEFAULT_MAC,
    UNSET,
    EmulatedDevice,
)
from .frame import FrameError, decode, encode, make_frame
from .legacy import LegacyModule, LegacyProfile
from .mcu import McuScript, mcu_frame
from .module import AuthMode, DeviceModule, Module, ModuleConfig, Output, Versions
from .products import (
    GATT_LAYOUTS,
    PRODUCTS,
    GattLayout,
    ModuleBuild,
    Outer,
    Path,
    Product,
    ProductInfo,
    Transport,
)


__all__ = [
    "A17C0",
    "A17C1",
    "A17C3",
    "A25X7",
    "A91B2",
    "A110B",
    "A1722",
    "A1761",
    "A1763",
    "A1765",
    "A1780",
    "A1783",
    "A1785",
    "A2345",
    "A2687",
    "AS220",
    "COMMAND_UUID",
    "DEFAULT_MAC",
    "GATT_LAYOUTS",
    "GATT_SERVICE_UUID",
    "PRODUCTS",
    "TELEMETRY_UUID",
    "UNSET",
    "AuthMode",
    "Clock",
    "DeviceModule",
    "EmulatedBleakBackend",
    "EmulatedDevice",
    "FrameError",
    "GattLayout",
    "LegacyModule",
    "LegacyProfile",
    "ManualClock",
    "McuScript",
    "Module",
    "ModuleBuild",
    "ModuleConfig",
    "MonotonicClock",
    "Outer",
    "Output",
    "Path",
    "Product",
    "ProductInfo",
    "Transport",
    "Versions",
    "decode",
    "encode",
    "make_frame",
    "mcu_frame",
]
